admin:
    path: /admin
    controller: App\Controller\SecurityController::admin

login:
    path: /login
    controller: App\Controller\SecurityController::login

register:
    path: /register
    controller: App\Controller\SecurityController::register

plants:
    path: /plants
    controller: App\Controller\PlantController::view

logout:
    path: /logout
    methods: GET

index:
    path: /
    controller: App\Controller\DefaultController::index
