admin:
    path: /admin
    controller: App\Controller\SecurityController::admin

login:
    path: /login
    controller: App\Controller\SecurityController::login

register:
    path: /register
    controller: App\Controller\SecurityController::register

logout:
    path: /logout
    methods: GET

index:
    path: /
    controller: App\Controller\DefaultController::index

plants:
    path: /plants
    controller: App\Controller\DefaultController::plants

garden:
    path: /garden
    controller: App\Controller\SecurityController::garden

account:
    path: /account
    controller: App\Controller\SecurityController::account