admin:
    path: /admin
    controller: App\Controller\SecurityController::admin

login:
    path: /login
    controller: App\Controller\SecurityController::login

register:
    path: /register
    controller: App\Controller\SecurityController::register

logout:
    path: /logout
    methods: GET

# GARDEN

index:
    path: /
    controller: App\Controller\GardenController::index

garden_create:
    path: /garden
    controller: App\Controller\GardenController::createGarden
