# ADMIN

admin:
    path: /admin
    controller: App\Controller\SecurityController::admin

plots:
    path: /plots
    controller: App\Controller\PlotController::viewAll

# AUTH

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    methods: GET

register:
    path: /register
    controller: App\Controller\SecurityController::register

# ACCOUNT

account:
    path: /account
    controller: App\Controller\SecurityController::account

# PLANTS

plantFamilies:
    path: /plant_families
    controller: App\Controller\PlantFamilyController::viewAll

plantFamily:
    path: /plant_family/{id}
    controller: App\Controller\PlantFamilyController::viewFamily

plants:
    path: /plants
    controller: App\Controller\PlantController::viewAll

plant:
    path: /plant/{id}
    controller: App\Controller\PlantController::viewPlant

# GARDEN

gardens:
    path: /gardens
    controller: App\Controller\GardenController::viewAll

garden:
    path: /garden/{id}
    controller: App\Controller\GardenController::viewGarden

index:
    path: /
    controller: App\Controller\GardenController::index

garden_create:
    path: /garden
    controller: App\Controller\GardenController::editgarden

garden_edit:
    path: /garden/{id}/edit
    controller: App\Controller\GardenController::editGarden

plot:
    path: /plot/{id}
    controller: App\Controller\PlotController::viewPlot