admin:
    path: /admin
    controller: App\Controller\SecurityController::admin

login:
    path: /login
    controller: App\Controller\SecurityController::login

register:
    path: /register
    controller: App\Controller\SecurityController::register

plantFamilies:
    path: /plant_families
    controller: App\Controller\PlantFamilyController::viewAll

logout:
    path: /logout
    methods: GET

index:
    path: /
    controller: App\Controller\DefaultController::index
